### ISSUE TITLE
2441TH thermostat- Database "insane", really ?

### ISSUE THREAD

**Issue by PhilippeLibioulle** [pfrommerd/insteon-terminal#1]
Hi, 

I think I found an error within linkdb.py

if lastVal != 0x0fff:
#			out("lastval = " + format(lastVal, 'x'))
			return False
It should be:

if lastVal != 0x1fff:
#			out("lastval = " + format(lastVal, 'x'))
			return False

Without the fix, I had always the same error (Database incomplete.. try again..) and was not able to add/remove any entry. I was still able to get database just because the error is hidden and not managed anyway. Just uncomment the line and it appears after getdb() as well

Once changed, everything works well, including after the thermostat is integrated with OpenHab. I can get all the various statuses and interact with the thermostat

Philippe

**Comment by berndpfrommer** [comment]
Philippe,
nice catch, that is indeed a bug. I never noticed that the top of the link database for the thermostat is not at 0x0fff (like for all other devices I know), but at 0x1fff.  Even the examples show it.
I suggest to fix it like this: 
1) in issane() the DB class should not check against 0x0fff or 0x1fff, but rather against a configurable member variable called "topOfDatabase". That variable should be set to a default of 0x0fff (most devices have that) in the DB constructor. A setter should be provided so it can be set by
2) the ThermostatDBBuilder, which sets it to 0x1fff.
Do you think you can do it and test against thermostat & another device (light switch?) that has the standard 0x0fff top of database?

Thanks!
Bernd

**Comment by PhilippeLibioulle** [comment]
Thanks for the feed-back.  I got your point, I was not aware of the difference between thermostat database layout and other devices layout. I will test it for sure and let you know
Btw, I faced another weird issue with serial port. Here is how things are connected. OpenHab runs on a Raspberry PI 2, connected over USB to a USB-to-serial adapter (Prolific) and then to an Insteon (serial) PLM.  Insteon Terminal and OpenHab compete to get access to serial port. Obviously, I turn OpenHab service Off when I debug using Insteon Terminal.  But, after a debugging session, I have to manually unlock the port ( i.e sudo rm /var/lock/LCK..ttyUSB0), otherwise OpenHab does not "see" the port. Just FYI.

Philippe

Date: Thu, 11 Feb 2016 19:12:47 -0800

**Comment by berndpfrommer** [comment]
I have lock issues, too, especially when I run insteonterminal as a different user than openhab. Then openhab can't remove the lock file and croaks.

**Comment by PhilippeLibioulle** [comment]
Hi Bernd, 
Here it is...
I added ...   self.db.setTopOfDatabase(0x1fff)  in ThermostatDBBuilder classI added a member variable named topOfDatabase with default value  0x0fff  in DB classI updated row 162 with...  if lastVal != self.topOfDatabase:
Tested with 2413S PLM, thermostat and dimmer 2477D using Insteon Terminal toolNow I can query and update database on all devices
Tested with OpenHab 1.8.1 as well
Feel free to comment, I'm a C# guy :-) 
Regards, 
Philippe

Date: Thu, 11 Feb 2016 19:12:47 -0800

**Comment by berndpfrommer** [comment]
Did you submit a pull request? I didn't see one....

**Comment by berndpfrommer** [comment]
Philippe, I can't see your pull request. Did you submit one?

**Comment by pfrommerd** [comment]
I saw the pull requests and merged them.
