### ISSUE TITLE
Added additional functionality for Motion Sensor, added support for hidden door sensors and leak sensors

### ISSUE THREAD

**Issue by tommycw1** [pfrommerd/insteon-terminal#11]
Hello,

I'd like to submit a patch with additional support for motion sensors and adding support for hidden door sensors and leak sensors.  I've attached my patch against the latest here.  I tried to create a pull request, but it didn't seem to want to let me do that.  Not sure if I was doing something wrong or if it was locked down?

The motion sensor doesn't seem to have available developer's notes, so I googled around and found some info on settings.  The Hidden Door Sensor and the Leak Sensor luckily did have these notes available.  This patch includes support for all of the features included in those notes.
[patch.zip](https://github.com/pfrommerd/insteon-terminal/files/1049247/patch.zip)

**Comment by pfrommerd** [comment]
Awesome! I haven't tested the motion sensor code (and can't test the hidden door sensor or leak sensor) but will push this to the repo as it seems to be in order.

Thank you very much for your improvements. I'm not certain why you couldn't create a pull request as anybody should be able to create a pull request. If you make another pull request in the future and run into the same issue, open an issue and I'll try and figure out what's going wrong.
