### ISSUE TITLE
adding devices + MQTT

### ISSUE THREAD

**Issue by nbs3** [pfrommerd/insteon-terminal#12]
hey 
i'm trying to add motion sensors to the lest to use their commands like the way in the decimation

# Example device definitions
# kp          = Keypad2487S("office_keypad", "30.0d.9f")
# th          = Thermostat2441TH("kitchen_thermostat", "32.f7.2c")
# modem       = Modem2413U("test_modem", "23.9b.65")
# closetLight = Switch2477S("closetLight", "25.65.d6")
# dimmer      = Dimmer2477D("dining_room_dinner", "20.ab.26")
# ledBulb = LEDBulb2672("ledBulb", "21.EB.DD");

but it did't work  . 

also i want to use MQTT to send the information do you have an idea how to start with that , i tried to understand the watch command their is no explain about that  
and thanks for all that great job you did

**Comment by pfrommerd** [comment]
Sorry, this project is not meant as a production tool to be integrated and is more geared towards understanding/reverse engineering the insteon device functionality (i.e a development tool). If you are looking to integrate MQTT with insteon devices, I would look at OpenHAB, which I believe supports what you are trying to do.

**Comment by nbs3** [comment]
thanks , 
but the first part about how to add devices
