### ISSUE TITLE
setOnLevel v. setOnLevelResponder (or how to set default on level and ramp rate)

### ISSUE THREAD

**Issue by johnofcamas** [pfrommerd/insteon-terminal#13]
I'm not sure how the api setOnLevelResponder works on a `Dimmer2477D`

The docs say: 

> sets (on level, ramp rate, button) for controller with "addr" and group "group" """

But I'm not sure which address and group to use.

Example, I have a switch with the following db:
```
>>> familyRoomFireplace.getdb()
getting db, be patient!
sent db query msg, incoming records: >>>  1 2 3 4
----- database -------
0fff modem                          44.86.3B  RESP  10101010 group: fe ON LVL:   0 RMPRT:  28 BUTTON:   0
0ff7 modem                          44.86.3B  CTRL  11100010 group: 01 ON LVL:   0 RMPRT:   0 BUTTON:   1
0fef 00.00.00                       00.00.00 (RESP) 00000010 group: 00 ON LVL:   0 RMPRT:   0 BUTTON:   0
0fe7 00.00.00                       00.00.00 (RESP) 00000000 group: 00 ON LVL:   0 RMPRT:   0 BUTTON:   0
----- end ------------
```

and I want to set the device to default to 50% brightness when turned on.  How can I do that?  Is `setOnLevelResponder` even the correct API for that?

**Comment by johnofcamas** [comment]
I'm going to follow up myself with a little bit more info after a bit of an investigation.

From what I can tell, there is no command (currently) for setting a devices 'default' on level and ramp rate.  This must either be done with Indigo software, or manually at the switch.  If I knew the raw command, perhaps the library could be fixed to add this capability?

**Comment by johnofcamas** [comment]
Another update.

I've turned on debug logging for Indigo and here are the raw commands for setting default level and ramp rate:
```
Aug 9, 2017, 2:15:32 PM
  Debug                           SENT: insteon 44.86.3B   29.E5.F5   15    2E 00
  Debug                           SENT: extended data 01 06 80 00 00 00 00 00 00 00 00 00 00 4B
  Debug                           RCVD: insteon 29.E5.F5   44.86.3B   25    2E 00
  Debug                           RCVD: ack from 29.E5.F5 for command 2E 00
  Debug                           waiting 58 for idle input queue
  Sent INSTEON                    "Family Room Fireplace" set local default on level (via extended message) to 50
  Debug                           timeout signal
  Debug                           SENT: insteon 44.86.3B   29.E5.F5   15    2E 00
  Debug                           SENT: extended data 01 05 1E 00 00 00 00 00 00 00 00 00 00 AE
  Debug                           RCVD: insteon 29.E5.F5   44.86.3B   25    2E 00
  Debug                           RCVD: ack from 29.E5.F5 for command 2E 00
  Sent INSTEON                    "Family Room Fireplace" set local ramp rate duration (via extended message) to 0.2 seconds
```

**Comment by johnofcamas** [comment]
No worries!  Thanks for responding.. I am really trying to get to the point where I can do these mgmt tasks from insteon-terminal instead of Indigo, and that is one of the last - biggest - things.

**Comment by pfrommerd** [comment]
Alright, I finally got around to adding and testing both commands to set on the on level for a given button as well as the button ramp rate. I've added them to all dimmers, meaning that you should be able to do dimmer.setButtonOnLevel(level, button) (Leave out button if you want it to default to button number 1)
and dimmer.setButtonRampRate(rate, button) (You can also leave out button here)
Rate is between 0x00 and 0x1f and level is between 0x00 and 0xFF.
Let me know if it works for you. I'm trying to fix some issues with rxtx regarding correct use of locking files on new versions linux, so there might be issues connecting to the serial port depending on what system you are using.

**Comment by johnofcamas** [comment]
Fantastic!  I'll try it out next time I get a chance.  Thanks!

**Comment by johnofcamas** [comment]
@pfrommerd It works!!!  Thank you very much -- any chance if it making its way into the openHAB insteonPLM plugin?
