### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by SuperDave51** [pfrommerd/insteon-terminal#24]
Attempting to install on the following system:
Hardware: Intel Q9650 on Dell 0G261D motherboard
OS: Ubuntu 18.04.1 LTS
JRE: OpenJDK 1.8.0_192
ANT: 1.10.3

I get through the instructions well enough.  My init.py file is comprised of the following entries:
from console_commands import *
from keypad2487S import *
from thermostat2441TH import *
from modem2413U import *
from switch2477S import *
from dimmer2477D import *
from ledBulb2672 import *

def connectToMyHub():
“”“connects to my insteon hub modem at pre-defined address”""
connectToHub(“insteonhub”, 25105, 1000, “MyHubLogin”, “MyHubPassword”)

#If you are using a legacy hub (pre-2014 hub)

def connectToMyLegacyHub():
“”“connects to my insteon hub modem at pre-defined address”""
connectToLegacyHub(“insteonhub”, 9761) # syntax is address, port (generally 9761)

def connectToMySerial():
“”“connects to my modem on pre-defined serial port”""

connectToSerial("/dev/ttyUSB0")

connectToMy…() function

connectToMySerial()

modem = Modem2413U(“house_plm”, “48.EF.F9”)
wall_switch = Switch2635(“wall_switch”, “36.6B.50”)

When I get to the end of the instructions and attempt to run with ./insteon-terminal, I receive the following:
BUILD FAILED
/etc/apt/insteon-terminal/build.xml:30: Directory /etc/apt/insteon-terminal/bin creation was not successful for an unknown reason
Total time: 0 seconds
Error: Could not find or load main class us.pfrommer.insteon.terminal.Main

Any thoughts on what I may have missed?  Thank you!
Dave

**Comment by pfrommerd** [comment]
Check the permissions you have on the insteon-terminal folder. I would guess you don't have write permissions.
