### ISSUE TITLE
I reverse engineered the I/O Linc if you want to implement it...

### ISSUE THREAD

**Issue by PaulWieland** [pfrommerd/insteon-terminal#27]
Saw this comment: https://github.com/pfrommerd/insteon-terminal/blob/2d14e4244b4cc1b8e8d42c1da9195e1e056b7a99/python/iolinc2450.py#L50

I have a pretty thorough I/O Linc NodeJS class written and tested if someone here wants to backport it.

https://github.com/apearson/insteon-plm/blob/master/src/devices/SensorActuatorDevice/IOLinc.ts

**Comment by pfrommerd** [comment]
The long term plan was to port everything to the new https://github.com/pfrommerd/python-insteon for a pure-python implementation with proper support for async operations, easy device database manipulation, and the like.

I've been working on other things and development has come to a (hopefully temporary stop), but if anywhere, that's probably where I'll add the iolinc functionality. Thanks for pointing this out though! I'm sure it'll be a huge help.
