### ISSUE TITLE
Error in Hidden door sensor code

### ISSUE THREAD

**Issue by tommycw1** [pfrommerd/insteon-terminal#31]
Hi,

I found an error in code that I probably submitted,  In hiddendoorsensor.py there is an error in the mask used for bit 1:

```
# Bit 0
if (rawflags & 0b00000001 == 1):
cleanupreport = "Send Cleanup Report"
else:
cleanupreport = "Don't Send Cleanup Report"
# Bit 1
if (rawflags & 0b00000100 == 2):
twogroups = "Send Open on Group 1 ON and Closed on Group 2 ON"
else:
twogroups = "Send both Open and Closed on Group 1 (On=Open and Off=Closed)"
# Bit 2
if (rawflags & 0b00000100 == 4):
openrepeat = "Send Repeated Open Commands (Every 5 mins for 50 mins)"
else:
openrepeat = "Don't Send Repeated Open Commands"
```

The mask for bit one should is currently the same as the mask for bit 2, but it should be  0b00000010.  So currently this code incorrectly shows the HDS is in one group mode no matter the actual setting.

**Comment by pfrommerd** [comment]
Thanks for reporting this! This seems like a pretty straightforward bug and will push the fix shortly.
