### ISSUE TITLE
linkdb.py Syntax Error

### ISSUE THREAD

**Issue by sciamachy** [pfrommerd/insteon-terminal#5]
Missed a colon...

SyntaxError: ("mismatched input '\\n' expecting COLON", ('python/linkdb.py', 162, 34, '\t\tif lastVal != self.topOfDatabase\n'))

**Comment by pfrommerd** [comment]
Sorry! Just fixed that.

**Comment by pfrommerd** [comment]
Let me know if it works

**Comment by sciamachy** [comment]
Looks good, thanks.
